services:
  scaffold-mcp:
    build:
      context: .
    container_name: scaffold-mcp-prod
    env_file:
      - .env
    stdin_open: true    # enables interactive input
    tty: true
    depends_on:
      neo4j:
        condition: service_healthy

  chromadb:
    image: chromadb/chroma:1.0.13
    container_name: scaffold-chromadb
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=TRUE
    volumes:
      - chroma_data:/data

  neo4j:
    image: neo4j:5
    container_name: scaffold-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_AUTH=none
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u $NEO4J_USER -p $NEO4J_PASSWORD 'RETURN 1'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  chroma_data:
  neo4j_data: