[tool.poetry]
name = "scaffold"
version = "0.1.0"
description = ""
authors = ["Beer Bears"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = "^2.0.41"
neo4j = "^5.28.1"
pydantic-settings = "^2.9.1"
asyncpg = "^0.30.0"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
fastmcp = "^0.1.0"
httpx = "^0.24.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
pytest-asyncio = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
