name: Docker Compose CI
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Tests .env
        run: cp .env.example .env

      - name: Validate compose.yaml
        run: docker compose config

  poetry-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Validate pyproject.toml
        run: poetry check

      - name: Install dependencies
        run: poetry install --no-root