name: Docker Compose CI
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Validate compose.yaml
        run: docker compose config

      - name: Build Docker images
        run: docker compose build --pull

      - name: Start containers
        run: docker compose up -d

      - name: Stop containers
        run: docker compose down -v
        if: always()