name: Unstable image build

on:
  push:
    tags: ["unstable-*"]

env:
  REGISTRY: ghcr.io
  BUILD_CONTEXT: .
  IMAGE_NAME: beer-bears/scaffold

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - id: poetry
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:unstable-latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.poetry.outputs.VERSION }}-unstable