name: Build and Push Docker Image

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      push_unstable:
        description: 'Push unstable image'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  BUILD_CONTEXT: ./src
  IMAGE_NAME: beer-bears/scaffold

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.push_unstable }}" == "true" ]]; then
            echo "tag=unstable" >> $GITHUB_OUTPUT
            echo "Using tag: unstable"
          else
            TAG=${GITHUB_REF#refs/tags/}
            echo "tag=${TAG}" >> $GITHUB_OUTPUT
            echo "Using tag: $TAG"
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
            ${{ github.event_name != 'workflow_dispatch' && format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME) || '' }}