name: Conventional PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  conventional-check:
    runs-on: ubuntu-latest
    steps:
        # Use Conventional PR Title from: http://github.com/marketplace/actions/conventional-pr-title
      - name: Conventional PR Title
        uses: aslafy-z/conventional-pr-title-action@v3.2.0