name: Conventional PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
        # Use Conventional PR Title from: http://github.com/marketplace/actions/conventional-pr-title
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}